---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgDdUc92IqcgcSHZIZwu30cLV+wWvlEW40WKMe3UWLUU6veBycKFo4pcG4ditMjZO6dUdU8zXZS0tbu0liPlhC2PMqM3qbHCUXnuAOa2nY4J7lYA3qku1E6HRLeOCXJrPJFLcSmGsvsKgreWEiziGOa0bkKm/6oZxscy00D38QOBDAb2dntCjaseSRjyTWEUxFKM/M4MFwGmJdaQIYMI415FcmTwf2nBKK7dfYm33EzdWz3Uodo2Gv80tEhiZfIESApHlicagMx2P4/ztFNtNzs8bPq8I+iz2X/I2HsgOD+pdrwoVwRuJ22jm11QrnX+rthQkLhNOfz/r9MGhNy8AqkJS3Ge7JHuCwsXYklpC0FCiA5QRL61++Dy8B/apo6ebuJCx3q5JfzoIkv1ejOC9GOQVlwy9qEq3BkI9Bt2/03GEVvuczH3B620DggnjpqClJdPqY7AAjBcqm48NAZ8sbwuKo7q5bTqJ7tCSDfJlrwKmx5NUk+7/VX7RHMxucM86wliSqAxN1KIwS35A01yN8yLJefgdT+2xKzVLykIHsvpv7uukqlgvAGUqAb6jWU3d2tmC/85nlsDEm27NRs7gZK/zeqTZC+mWF0K7abK3iP1tCT14GYMnVDqZ533f9+gBzHuPAkWXIkpArHpzrVRn7JFJ0rhrDXSJJrs55IvMPIE8GLqw0xtJkVTjN3Oe64ysG8zj3l++YI4
    username: AgAw6lS629bWou9rMl5afCc0bhi0VjWvedt1EapYP5dTN8s0Tqn7WnaNLi12JVPoFNALcasczfCa10VkFqdXfEXCF5yGhCnYrW/NmxExK3YyOr4N8CrpG7e6+H5tn2a3JXbD07uQ/hMepMLvyowHeuVei/vxpzKRGl90Y1r9bQtb46j7qxiOMD0bDX+d5uqc9c35rNqoD87UPPYrXXQoLvugumy7E6N5DaUYVC5nQeJh0EQcmoByjbwb+vosYndCzuNy0QWKgcHBlNi93m5wdGItDeKziAg4C4U+X+qIpldw1JRHWBda9jHAQQ1eKY1sHnA0GtMIbOryySb5a8cMne3UqTtW88QFMBcfYFKRAfPIpWYSwdbxSLfBFemlAkvVWsXqu4HI8vQd6imQpPJ6NC5ZWjFN0/Wh3hfkBCnvKKzJaR1EMuVWEpWDgo9gWq5kAyH+BzNj2VyCCbspGN6b/0Pj1+JjarWQhIAOC7K6Gp4jEIAde2uHsLZu7jhHE8Dr8+gUN+rV/V1SyfFFTLtXq3Fg3V9b4OioPrDpXa6oCE6i07TqqOH+GdDtbbOYWfPERfZCeYDcEODBPNWED07JUrFstYqGZeHCXh8aO6EZyOXvWcf3jGQlNo1OZFd/M9e1O+gUnfZOAwfPRxzlret4ygrwWyA1DTwEuAuZwQfl22VuXdtQXgMzfucz/DALNfE8QbHF0udDBg==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
